import { execSync } from "child_process";
import fs from "fs";
import path from "path";

const CONTRACT_NAME = "NebulaCareRegistry";
const hardhatRoot = path.resolve("../contracts/animalcare-hardhat");
const deploymentsDir = path.join(hardhatRoot, "deployments");
const outDir = path.resolve("./abi");
const artifactPath = path.join(
  hardhatRoot,
  "artifacts/contracts/NebulaCareRegistry.sol/NebulaCareRegistry.json"
);

if (!fs.existsSync(outDir)) {
  fs.mkdirSync(outDir, { recursive: true });
}

function ensureDeployment(network) {
  const dir = path.join(deploymentsDir, network);
  if (!fs.existsSync(dir) && network === "localhost") {
    execSync("./deploy-hardhat-node.sh", {
      cwd: path.resolve("./scripts"),
      stdio: "inherit"
    });
  }
  if (!fs.existsSync(dir)) {
    throw new Error(
      `Missing deployment for ${network}. Run 'npx hardhat deploy --network ${network}' inside ${hardhatRoot} and retry.`
    );
  }
  return dir;
}

function loadDeployment(network, chainId, optional) {
  try {
    let dir = path.join(deploymentsDir, network);
    if (!fs.existsSync(dir)) {
      if (optional) return undefined;
      dir = ensureDeployment(network);
    }
    const file = path.join(dir, `${CONTRACT_NAME}.json`);
    const json = JSON.parse(fs.readFileSync(file, "utf-8"));
    json.chainId = chainId;
    return json;
  } catch (error) {
    if (optional) {
      return undefined;
    }
    throw error;
  }
}

function loadArtifactFallback() {
  if (!fs.existsSync(artifactPath)) {
    throw new Error("Contract artifact missing. Run 'npm run build' inside the contracts workspace first.");
  }
  const artifact = JSON.parse(fs.readFileSync(artifactPath, "utf-8"));
  return {
    address: "0x5FbDB2315678afecb367f032d93F642f64180aa3",
    abi: artifact.abi,
    chainId: 31337
  };
}

const localhost = loadDeployment("localhost", 31337, true) ?? loadArtifactFallback();
const sepolia =
  loadDeployment("sepolia", 11155111, true) ??
  { address: "0x0000000000000000000000000000000000000000", abi: localhost.abi };

if (JSON.stringify(localhost.abi) !== JSON.stringify(sepolia.abi)) {
  throw new Error("ABIs differ across networks. Redeploy to synchronise before regenerating.");
}

const abiTs = `
/*
  File generated by scripts/genabi.mjs
*/
export const ${CONTRACT_NAME}ABI = ${JSON.stringify({ abi: localhost.abi }, null, 2)} as const;
`;

const addressesTs = `
/*
  File generated by scripts/genabi.mjs
*/
export const ${CONTRACT_NAME}Addresses = {
  "31337": { address: "${localhost.address}", chainId: 31337, chainName: "hardhat" },
  "11155111": { address: "${sepolia.address}", chainId: 11155111, chainName: "sepolia" }
} as const;
`;

fs.writeFileSync(path.join(outDir, `${CONTRACT_NAME}ABI.ts`), abiTs, "utf-8");
fs.writeFileSync(path.join(outDir, `${CONTRACT_NAME}Addresses.ts`), addressesTs, "utf-8");

console.log("ABI and address mapping refreshed.");

