
/*
  File generated by scripts/genabi.mjs
*/
export const NebulaCareRegistryAddresses = {
  "31337": { address: "0x5FbDB2315678afecb367f032d93F642f64180aa3", chainId: 31337, chainName: "hardhat" },
  "11155111": { address: "0xF003c782B7ddc094dAC16C6cFbCc9720693eFfcb", chainId: 11155111, chainName: "sepolia" }
} as const;
