
/*
  File generated by scripts/genabi.mjs
*/
export const NebulaCareRegistryABI = {
  "abi": [
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "admin_",
          "type": "address"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "constructor"
    },
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "companionId",
          "type": "uint256"
        }
      ],
      "name": "CompanionNotFound",
      "type": "error"
    },
    {
      "inputs": [],
      "name": "InvalidInput",
      "type": "error"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "viewer",
          "type": "address"
        }
      ],
      "name": "InvalidViewer",
      "type": "error"
    },
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "companionId",
          "type": "uint256"
        },
        {
          "internalType": "address",
          "name": "caller",
          "type": "address"
        }
      ],
      "name": "NotAuroraAuthorized",
      "type": "error"
    },
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "companionId",
          "type": "uint256"
        },
        {
          "internalType": "address",
          "name": "caller",
          "type": "address"
        }
      ],
      "name": "NotCompanionOwner",
      "type": "error"
    },
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "storyId",
          "type": "uint256"
        }
      ],
      "name": "StoryAlreadyHasVital",
      "type": "error"
    },
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "storyId",
          "type": "uint256"
        }
      ],
      "name": "StoryNotFound",
      "type": "error"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "internalType": "uint256",
          "name": "companionId",
          "type": "uint256"
        },
        {
          "indexed": true,
          "internalType": "uint256",
          "name": "storyId",
          "type": "uint256"
        },
        {
          "indexed": false,
          "internalType": "string",
          "name": "certCID",
          "type": "string"
        }
      ],
      "name": "AuroraCertificateFlagged",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "internalType": "address",
          "name": "verifier",
          "type": "address"
        },
        {
          "indexed": false,
          "internalType": "bool",
          "name": "approved",
          "type": "bool"
        }
      ],
      "name": "AuroraVerifierUpdated",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "internalType": "uint256",
          "name": "companionId",
          "type": "uint256"
        },
        {
          "indexed": false,
          "internalType": "string",
          "name": "profileCID",
          "type": "string"
        },
        {
          "indexed": false,
          "internalType": "uint8",
          "name": "privacyLevel",
          "type": "uint8"
        }
      ],
      "name": "CompanionProfileRefreshed",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "internalType": "uint256",
          "name": "companionId",
          "type": "uint256"
        },
        {
          "indexed": true,
          "internalType": "address",
          "name": "creator",
          "type": "address"
        },
        {
          "indexed": false,
          "internalType": "string",
          "name": "profileCID",
          "type": "string"
        },
        {
          "indexed": false,
          "internalType": "uint8",
          "name": "privacyLevel",
          "type": "uint8"
        }
      ],
      "name": "CompanionRegistered",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "internalType": "uint256",
          "name": "companionId",
          "type": "uint256"
        },
        {
          "indexed": true,
          "internalType": "address",
          "name": "viewer",
          "type": "address"
        }
      ],
      "name": "ConstellationViewerGranted",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "internalType": "uint256",
          "name": "companionId",
          "type": "uint256"
        },
        {
          "indexed": true,
          "internalType": "address",
          "name": "viewer",
          "type": "address"
        }
      ],
      "name": "ConstellationViewerRevoked",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "internalType": "uint256",
          "name": "companionId",
          "type": "uint256"
        },
        {
          "indexed": true,
          "internalType": "uint256",
          "name": "storyId",
          "type": "uint256"
        },
        {
          "indexed": true,
          "internalType": "address",
          "name": "verifier",
          "type": "address"
        },
        {
          "indexed": false,
          "internalType": "string",
          "name": "verifyCID",
          "type": "string"
        },
        {
          "indexed": false,
          "internalType": "bool",
          "name": "approved",
          "type": "bool"
        }
      ],
      "name": "StoryAttested",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "internalType": "uint256",
          "name": "companionId",
          "type": "uint256"
        },
        {
          "indexed": true,
          "internalType": "uint256",
          "name": "storyId",
          "type": "uint256"
        },
        {
          "indexed": true,
          "internalType": "address",
          "name": "author",
          "type": "address"
        },
        {
          "indexed": false,
          "internalType": "string",
          "name": "logCID",
          "type": "string"
        },
        {
          "indexed": false,
          "internalType": "uint8",
          "name": "eventType",
          "type": "uint8"
        },
        {
          "indexed": false,
          "internalType": "bool",
          "name": "withVital",
          "type": "bool"
        }
      ],
      "name": "StoryCaptured",
      "type": "event"
    },
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "companionId",
          "type": "uint256"
        },
        {
          "internalType": "address",
          "name": "viewer",
          "type": "address"
        }
      ],
      "name": "allowConstellationViewer",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "storyId",
          "type": "uint256"
        },
        {
          "internalType": "string",
          "name": "verifyCID",
          "type": "string"
        },
        {
          "internalType": "bool",
          "name": "approved",
          "type": "bool"
        }
      ],
      "name": "attestStory",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "companionId",
          "type": "uint256"
        },
        {
          "internalType": "address",
          "name": "viewer",
          "type": "address"
        }
      ],
      "name": "banConstellationViewer",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "storyId",
          "type": "uint256"
        },
        {
          "internalType": "externalEuint64",
          "name": "encryptedVital",
          "type": "bytes32"
        },
        {
          "internalType": "bytes",
          "name": "inputProof",
          "type": "bytes"
        }
      ],
      "name": "embedVitalIntoStory",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "companionId",
          "type": "uint256"
        },
        {
          "internalType": "uint256",
          "name": "storyId",
          "type": "uint256"
        },
        {
          "internalType": "string",
          "name": "certCID",
          "type": "string"
        }
      ],
      "name": "flagAuroraCertificate",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "companionId",
          "type": "uint256"
        }
      ],
      "name": "getCompanion",
      "outputs": [
        {
          "components": [
            {
              "internalType": "uint256",
              "name": "companionId",
              "type": "uint256"
            },
            {
              "internalType": "string",
              "name": "profileCID",
              "type": "string"
            },
            {
              "internalType": "uint8",
              "name": "privacyLevel",
              "type": "uint8"
            },
            {
              "internalType": "uint64",
              "name": "createdAt",
              "type": "uint64"
            },
            {
              "internalType": "uint64",
              "name": "updatedAt",
              "type": "uint64"
            },
            {
              "internalType": "address[]",
              "name": "owners",
              "type": "address[]"
            },
            {
              "internalType": "uint256",
              "name": "storyCount",
              "type": "uint256"
            },
            {
              "internalType": "bool",
              "name": "hasVitalAura",
              "type": "bool"
            }
          ],
          "internalType": "struct NebulaCareRegistry.CompanionView",
          "name": "viewData",
          "type": "tuple"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "companionId",
          "type": "uint256"
        }
      ],
      "name": "getCompanionVitalSummary",
      "outputs": [
        {
          "internalType": "euint64",
          "name": "sum",
          "type": "bytes32"
        },
        {
          "internalType": "euint32",
          "name": "count",
          "type": "bytes32"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "companionId",
          "type": "uint256"
        },
        {
          "internalType": "uint256",
          "name": "start",
          "type": "uint256"
        },
        {
          "internalType": "uint256",
          "name": "count",
          "type": "uint256"
        }
      ],
      "name": "getStories",
      "outputs": [
        {
          "components": [
            {
              "internalType": "uint256",
              "name": "storyId",
              "type": "uint256"
            },
            {
              "internalType": "uint256",
              "name": "companionId",
              "type": "uint256"
            },
            {
              "internalType": "address",
              "name": "author",
              "type": "address"
            },
            {
              "internalType": "string",
              "name": "logCID",
              "type": "string"
            },
            {
              "internalType": "uint8",
              "name": "eventType",
              "type": "uint8"
            },
            {
              "internalType": "uint64",
              "name": "timestamp",
              "type": "uint64"
            },
            {
              "internalType": "bool",
              "name": "verified",
              "type": "bool"
            },
            {
              "internalType": "address",
              "name": "verifier",
              "type": "address"
            },
            {
              "internalType": "string",
              "name": "verifyCID",
              "type": "string"
            },
            {
              "internalType": "bool",
              "name": "hasEncryptedVital",
              "type": "bool"
            }
          ],
          "internalType": "struct NebulaCareRegistry.StoryView[]",
          "name": "stories",
          "type": "tuple[]"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "storyId",
          "type": "uint256"
        }
      ],
      "name": "getStoryVitalHandle",
      "outputs": [
        {
          "internalType": "euint64",
          "name": "vital",
          "type": "bytes32"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "account",
          "type": "address"
        }
      ],
      "name": "isAuroraVerifier",
      "outputs": [
        {
          "internalType": "bool",
          "name": "",
          "type": "bool"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "companionId",
          "type": "uint256"
        },
        {
          "internalType": "address",
          "name": "account",
          "type": "address"
        }
      ],
      "name": "isCompanionGuardian",
      "outputs": [
        {
          "internalType": "bool",
          "name": "",
          "type": "bool"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "companionId",
          "type": "uint256"
        },
        {
          "internalType": "address",
          "name": "account",
          "type": "address"
        }
      ],
      "name": "isConstellationViewer",
      "outputs": [
        {
          "internalType": "bool",
          "name": "",
          "type": "bool"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "nextCompanionId",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "nextStoryId",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "protocolId",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "pure",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "companionId",
          "type": "uint256"
        },
        {
          "internalType": "string",
          "name": "logCID",
          "type": "string"
        },
        {
          "internalType": "uint8",
          "name": "eventType",
          "type": "uint8"
        }
      ],
      "name": "recordStory",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "storyId",
          "type": "uint256"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "companionId",
          "type": "uint256"
        },
        {
          "internalType": "string",
          "name": "logCID",
          "type": "string"
        },
        {
          "internalType": "uint8",
          "name": "eventType",
          "type": "uint8"
        },
        {
          "internalType": "externalEuint64",
          "name": "encryptedVital",
          "type": "bytes32"
        },
        {
          "internalType": "bytes",
          "name": "inputProof",
          "type": "bytes"
        }
      ],
      "name": "recordStoryWithVital",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "storyId",
          "type": "uint256"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "companionId",
          "type": "uint256"
        },
        {
          "internalType": "string",
          "name": "profileCID",
          "type": "string"
        },
        {
          "internalType": "uint8",
          "name": "privacyLevel",
          "type": "uint8"
        }
      ],
      "name": "refreshCompanionProfile",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "string",
          "name": "profileCID",
          "type": "string"
        },
        {
          "internalType": "address[]",
          "name": "coOwners",
          "type": "address[]"
        },
        {
          "internalType": "uint8",
          "name": "privacyLevel",
          "type": "uint8"
        }
      ],
      "name": "registerCompanion",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "companionId",
          "type": "uint256"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "newAdmin",
          "type": "address"
        }
      ],
      "name": "setAdmin",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "account",
          "type": "address"
        },
        {
          "internalType": "bool",
          "name": "approved",
          "type": "bool"
        }
      ],
      "name": "setVerifier",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "stardustAdmin",
      "outputs": [
        {
          "internalType": "address",
          "name": "",
          "type": "address"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "companionId",
          "type": "uint256"
        },
        {
          "internalType": "externalEuint64",
          "name": "deltaVital",
          "type": "bytes32"
        },
        {
          "internalType": "bytes",
          "name": "inputProof",
          "type": "bytes"
        }
      ],
      "name": "trackVitalShift",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    }
  ]
} as const;
