/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace NebulaCareRegistry {
  export type CompanionViewStruct = {
    companionId: BigNumberish;
    profileCID: string;
    privacyLevel: BigNumberish;
    createdAt: BigNumberish;
    updatedAt: BigNumberish;
    owners: AddressLike[];
    storyCount: BigNumberish;
    hasVitalAura: boolean;
  };

  export type CompanionViewStructOutput = [
    companionId: bigint,
    profileCID: string,
    privacyLevel: bigint,
    createdAt: bigint,
    updatedAt: bigint,
    owners: string[],
    storyCount: bigint,
    hasVitalAura: boolean
  ] & {
    companionId: bigint;
    profileCID: string;
    privacyLevel: bigint;
    createdAt: bigint;
    updatedAt: bigint;
    owners: string[];
    storyCount: bigint;
    hasVitalAura: boolean;
  };

  export type StoryViewStruct = {
    storyId: BigNumberish;
    companionId: BigNumberish;
    author: AddressLike;
    logCID: string;
    eventType: BigNumberish;
    timestamp: BigNumberish;
    verified: boolean;
    verifier: AddressLike;
    verifyCID: string;
    hasEncryptedVital: boolean;
  };

  export type StoryViewStructOutput = [
    storyId: bigint,
    companionId: bigint,
    author: string,
    logCID: string,
    eventType: bigint,
    timestamp: bigint,
    verified: boolean,
    verifier: string,
    verifyCID: string,
    hasEncryptedVital: boolean
  ] & {
    storyId: bigint;
    companionId: bigint;
    author: string;
    logCID: string;
    eventType: bigint;
    timestamp: bigint;
    verified: boolean;
    verifier: string;
    verifyCID: string;
    hasEncryptedVital: boolean;
  };
}

export interface NebulaCareRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "allowConstellationViewer"
      | "attestStory"
      | "banConstellationViewer"
      | "confidentialProtocolId"
      | "embedVitalIntoStory"
      | "flagAuroraCertificate"
      | "getCompanion"
      | "getCompanionVitalSummary"
      | "getStories"
      | "getStoryVitalHandle"
      | "isAuroraVerifier"
      | "isCompanionGuardian"
      | "isConstellationViewer"
      | "nextCompanionId"
      | "nextStoryId"
      | "recordStory"
      | "recordStoryWithVital"
      | "refreshCompanionProfile"
      | "registerCompanion"
      | "setAdmin"
      | "setVerifier"
      | "stardustAdmin"
      | "trackVitalShift"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AuroraCertificateFlagged"
      | "AuroraVerifierUpdated"
      | "CompanionProfileRefreshed"
      | "CompanionRegistered"
      | "ConstellationViewerGranted"
      | "ConstellationViewerRevoked"
      | "StoryAttested"
      | "StoryCaptured"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "allowConstellationViewer",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "attestStory",
    values: [BigNumberish, string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "banConstellationViewer",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "embedVitalIntoStory",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "flagAuroraCertificate",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getCompanion",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCompanionVitalSummary",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getStories",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getStoryVitalHandle",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isAuroraVerifier",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isCompanionGuardian",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isConstellationViewer",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "nextCompanionId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nextStoryId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "recordStory",
    values: [BigNumberish, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recordStoryWithVital",
    values: [BigNumberish, string, BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "refreshCompanionProfile",
    values: [BigNumberish, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerCompanion",
    values: [string, AddressLike[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setVerifier",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "stardustAdmin",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "trackVitalShift",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "allowConstellationViewer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "attestStory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "banConstellationViewer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "embedVitalIntoStory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "flagAuroraCertificate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCompanion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCompanionVitalSummary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getStories", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getStoryVitalHandle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAuroraVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isCompanionGuardian",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isConstellationViewer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextCompanionId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextStoryId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordStory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordStoryWithVital",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "refreshCompanionProfile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerCompanion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setAdmin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stardustAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "trackVitalShift",
    data: BytesLike
  ): Result;
}

export namespace AuroraCertificateFlaggedEvent {
  export type InputTuple = [
    companionId: BigNumberish,
    storyId: BigNumberish,
    certCID: string
  ];
  export type OutputTuple = [
    companionId: bigint,
    storyId: bigint,
    certCID: string
  ];
  export interface OutputObject {
    companionId: bigint;
    storyId: bigint;
    certCID: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AuroraVerifierUpdatedEvent {
  export type InputTuple = [verifier: AddressLike, approved: boolean];
  export type OutputTuple = [verifier: string, approved: boolean];
  export interface OutputObject {
    verifier: string;
    approved: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CompanionProfileRefreshedEvent {
  export type InputTuple = [
    companionId: BigNumberish,
    profileCID: string,
    privacyLevel: BigNumberish
  ];
  export type OutputTuple = [
    companionId: bigint,
    profileCID: string,
    privacyLevel: bigint
  ];
  export interface OutputObject {
    companionId: bigint;
    profileCID: string;
    privacyLevel: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CompanionRegisteredEvent {
  export type InputTuple = [
    companionId: BigNumberish,
    creator: AddressLike,
    profileCID: string,
    privacyLevel: BigNumberish
  ];
  export type OutputTuple = [
    companionId: bigint,
    creator: string,
    profileCID: string,
    privacyLevel: bigint
  ];
  export interface OutputObject {
    companionId: bigint;
    creator: string;
    profileCID: string;
    privacyLevel: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ConstellationViewerGrantedEvent {
  export type InputTuple = [companionId: BigNumberish, viewer: AddressLike];
  export type OutputTuple = [companionId: bigint, viewer: string];
  export interface OutputObject {
    companionId: bigint;
    viewer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ConstellationViewerRevokedEvent {
  export type InputTuple = [companionId: BigNumberish, viewer: AddressLike];
  export type OutputTuple = [companionId: bigint, viewer: string];
  export interface OutputObject {
    companionId: bigint;
    viewer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StoryAttestedEvent {
  export type InputTuple = [
    companionId: BigNumberish,
    storyId: BigNumberish,
    verifier: AddressLike,
    verifyCID: string,
    approved: boolean
  ];
  export type OutputTuple = [
    companionId: bigint,
    storyId: bigint,
    verifier: string,
    verifyCID: string,
    approved: boolean
  ];
  export interface OutputObject {
    companionId: bigint;
    storyId: bigint;
    verifier: string;
    verifyCID: string;
    approved: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StoryCapturedEvent {
  export type InputTuple = [
    companionId: BigNumberish,
    storyId: BigNumberish,
    author: AddressLike,
    logCID: string,
    eventType: BigNumberish,
    withVital: boolean
  ];
  export type OutputTuple = [
    companionId: bigint,
    storyId: bigint,
    author: string,
    logCID: string,
    eventType: bigint,
    withVital: boolean
  ];
  export interface OutputObject {
    companionId: bigint;
    storyId: bigint;
    author: string;
    logCID: string;
    eventType: bigint;
    withVital: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface NebulaCareRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): NebulaCareRegistry;
  waitForDeployment(): Promise<this>;

  interface: NebulaCareRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  allowConstellationViewer: TypedContractMethod<
    [companionId: BigNumberish, viewer: AddressLike],
    [void],
    "nonpayable"
  >;

  attestStory: TypedContractMethod<
    [storyId: BigNumberish, verifyCID: string, approved: boolean],
    [void],
    "nonpayable"
  >;

  banConstellationViewer: TypedContractMethod<
    [companionId: BigNumberish, viewer: AddressLike],
    [void],
    "nonpayable"
  >;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  embedVitalIntoStory: TypedContractMethod<
    [storyId: BigNumberish, encryptedVital: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  flagAuroraCertificate: TypedContractMethod<
    [companionId: BigNumberish, storyId: BigNumberish, certCID: string],
    [void],
    "nonpayable"
  >;

  getCompanion: TypedContractMethod<
    [companionId: BigNumberish],
    [NebulaCareRegistry.CompanionViewStructOutput],
    "view"
  >;

  getCompanionVitalSummary: TypedContractMethod<
    [companionId: BigNumberish],
    [[string, string] & { sum: string; count: string }],
    "view"
  >;

  getStories: TypedContractMethod<
    [companionId: BigNumberish, start: BigNumberish, count: BigNumberish],
    [NebulaCareRegistry.StoryViewStructOutput[]],
    "view"
  >;

  getStoryVitalHandle: TypedContractMethod<
    [storyId: BigNumberish],
    [string],
    "view"
  >;

  isAuroraVerifier: TypedContractMethod<
    [account: AddressLike],
    [boolean],
    "view"
  >;

  isCompanionGuardian: TypedContractMethod<
    [companionId: BigNumberish, account: AddressLike],
    [boolean],
    "view"
  >;

  isConstellationViewer: TypedContractMethod<
    [companionId: BigNumberish, account: AddressLike],
    [boolean],
    "view"
  >;

  nextCompanionId: TypedContractMethod<[], [bigint], "view">;

  nextStoryId: TypedContractMethod<[], [bigint], "view">;

  recordStory: TypedContractMethod<
    [companionId: BigNumberish, logCID: string, eventType: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  recordStoryWithVital: TypedContractMethod<
    [
      companionId: BigNumberish,
      logCID: string,
      eventType: BigNumberish,
      encryptedVital: BytesLike,
      inputProof: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  refreshCompanionProfile: TypedContractMethod<
    [companionId: BigNumberish, profileCID: string, privacyLevel: BigNumberish],
    [void],
    "nonpayable"
  >;

  registerCompanion: TypedContractMethod<
    [profileCID: string, coOwners: AddressLike[], privacyLevel: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  setAdmin: TypedContractMethod<[newAdmin: AddressLike], [void], "nonpayable">;

  setVerifier: TypedContractMethod<
    [account: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;

  stardustAdmin: TypedContractMethod<[], [string], "view">;

  trackVitalShift: TypedContractMethod<
    [companionId: BigNumberish, deltaVital: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "allowConstellationViewer"
  ): TypedContractMethod<
    [companionId: BigNumberish, viewer: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "attestStory"
  ): TypedContractMethod<
    [storyId: BigNumberish, verifyCID: string, approved: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "banConstellationViewer"
  ): TypedContractMethod<
    [companionId: BigNumberish, viewer: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "embedVitalIntoStory"
  ): TypedContractMethod<
    [storyId: BigNumberish, encryptedVital: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "flagAuroraCertificate"
  ): TypedContractMethod<
    [companionId: BigNumberish, storyId: BigNumberish, certCID: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getCompanion"
  ): TypedContractMethod<
    [companionId: BigNumberish],
    [NebulaCareRegistry.CompanionViewStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCompanionVitalSummary"
  ): TypedContractMethod<
    [companionId: BigNumberish],
    [[string, string] & { sum: string; count: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getStories"
  ): TypedContractMethod<
    [companionId: BigNumberish, start: BigNumberish, count: BigNumberish],
    [NebulaCareRegistry.StoryViewStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getStoryVitalHandle"
  ): TypedContractMethod<[storyId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "isAuroraVerifier"
  ): TypedContractMethod<[account: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isCompanionGuardian"
  ): TypedContractMethod<
    [companionId: BigNumberish, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isConstellationViewer"
  ): TypedContractMethod<
    [companionId: BigNumberish, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextCompanionId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextStoryId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "recordStory"
  ): TypedContractMethod<
    [companionId: BigNumberish, logCID: string, eventType: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recordStoryWithVital"
  ): TypedContractMethod<
    [
      companionId: BigNumberish,
      logCID: string,
      eventType: BigNumberish,
      encryptedVital: BytesLike,
      inputProof: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "refreshCompanionProfile"
  ): TypedContractMethod<
    [companionId: BigNumberish, profileCID: string, privacyLevel: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerCompanion"
  ): TypedContractMethod<
    [profileCID: string, coOwners: AddressLike[], privacyLevel: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAdmin"
  ): TypedContractMethod<[newAdmin: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setVerifier"
  ): TypedContractMethod<
    [account: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "stardustAdmin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "trackVitalShift"
  ): TypedContractMethod<
    [companionId: BigNumberish, deltaVital: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AuroraCertificateFlagged"
  ): TypedContractEvent<
    AuroraCertificateFlaggedEvent.InputTuple,
    AuroraCertificateFlaggedEvent.OutputTuple,
    AuroraCertificateFlaggedEvent.OutputObject
  >;
  getEvent(
    key: "AuroraVerifierUpdated"
  ): TypedContractEvent<
    AuroraVerifierUpdatedEvent.InputTuple,
    AuroraVerifierUpdatedEvent.OutputTuple,
    AuroraVerifierUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "CompanionProfileRefreshed"
  ): TypedContractEvent<
    CompanionProfileRefreshedEvent.InputTuple,
    CompanionProfileRefreshedEvent.OutputTuple,
    CompanionProfileRefreshedEvent.OutputObject
  >;
  getEvent(
    key: "CompanionRegistered"
  ): TypedContractEvent<
    CompanionRegisteredEvent.InputTuple,
    CompanionRegisteredEvent.OutputTuple,
    CompanionRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "ConstellationViewerGranted"
  ): TypedContractEvent<
    ConstellationViewerGrantedEvent.InputTuple,
    ConstellationViewerGrantedEvent.OutputTuple,
    ConstellationViewerGrantedEvent.OutputObject
  >;
  getEvent(
    key: "ConstellationViewerRevoked"
  ): TypedContractEvent<
    ConstellationViewerRevokedEvent.InputTuple,
    ConstellationViewerRevokedEvent.OutputTuple,
    ConstellationViewerRevokedEvent.OutputObject
  >;
  getEvent(
    key: "StoryAttested"
  ): TypedContractEvent<
    StoryAttestedEvent.InputTuple,
    StoryAttestedEvent.OutputTuple,
    StoryAttestedEvent.OutputObject
  >;
  getEvent(
    key: "StoryCaptured"
  ): TypedContractEvent<
    StoryCapturedEvent.InputTuple,
    StoryCapturedEvent.OutputTuple,
    StoryCapturedEvent.OutputObject
  >;

  filters: {
    "AuroraCertificateFlagged(uint256,uint256,string)": TypedContractEvent<
      AuroraCertificateFlaggedEvent.InputTuple,
      AuroraCertificateFlaggedEvent.OutputTuple,
      AuroraCertificateFlaggedEvent.OutputObject
    >;
    AuroraCertificateFlagged: TypedContractEvent<
      AuroraCertificateFlaggedEvent.InputTuple,
      AuroraCertificateFlaggedEvent.OutputTuple,
      AuroraCertificateFlaggedEvent.OutputObject
    >;

    "AuroraVerifierUpdated(address,bool)": TypedContractEvent<
      AuroraVerifierUpdatedEvent.InputTuple,
      AuroraVerifierUpdatedEvent.OutputTuple,
      AuroraVerifierUpdatedEvent.OutputObject
    >;
    AuroraVerifierUpdated: TypedContractEvent<
      AuroraVerifierUpdatedEvent.InputTuple,
      AuroraVerifierUpdatedEvent.OutputTuple,
      AuroraVerifierUpdatedEvent.OutputObject
    >;

    "CompanionProfileRefreshed(uint256,string,uint8)": TypedContractEvent<
      CompanionProfileRefreshedEvent.InputTuple,
      CompanionProfileRefreshedEvent.OutputTuple,
      CompanionProfileRefreshedEvent.OutputObject
    >;
    CompanionProfileRefreshed: TypedContractEvent<
      CompanionProfileRefreshedEvent.InputTuple,
      CompanionProfileRefreshedEvent.OutputTuple,
      CompanionProfileRefreshedEvent.OutputObject
    >;

    "CompanionRegistered(uint256,address,string,uint8)": TypedContractEvent<
      CompanionRegisteredEvent.InputTuple,
      CompanionRegisteredEvent.OutputTuple,
      CompanionRegisteredEvent.OutputObject
    >;
    CompanionRegistered: TypedContractEvent<
      CompanionRegisteredEvent.InputTuple,
      CompanionRegisteredEvent.OutputTuple,
      CompanionRegisteredEvent.OutputObject
    >;

    "ConstellationViewerGranted(uint256,address)": TypedContractEvent<
      ConstellationViewerGrantedEvent.InputTuple,
      ConstellationViewerGrantedEvent.OutputTuple,
      ConstellationViewerGrantedEvent.OutputObject
    >;
    ConstellationViewerGranted: TypedContractEvent<
      ConstellationViewerGrantedEvent.InputTuple,
      ConstellationViewerGrantedEvent.OutputTuple,
      ConstellationViewerGrantedEvent.OutputObject
    >;

    "ConstellationViewerRevoked(uint256,address)": TypedContractEvent<
      ConstellationViewerRevokedEvent.InputTuple,
      ConstellationViewerRevokedEvent.OutputTuple,
      ConstellationViewerRevokedEvent.OutputObject
    >;
    ConstellationViewerRevoked: TypedContractEvent<
      ConstellationViewerRevokedEvent.InputTuple,
      ConstellationViewerRevokedEvent.OutputTuple,
      ConstellationViewerRevokedEvent.OutputObject
    >;

    "StoryAttested(uint256,uint256,address,string,bool)": TypedContractEvent<
      StoryAttestedEvent.InputTuple,
      StoryAttestedEvent.OutputTuple,
      StoryAttestedEvent.OutputObject
    >;
    StoryAttested: TypedContractEvent<
      StoryAttestedEvent.InputTuple,
      StoryAttestedEvent.OutputTuple,
      StoryAttestedEvent.OutputObject
    >;

    "StoryCaptured(uint256,uint256,address,string,uint8,bool)": TypedContractEvent<
      StoryCapturedEvent.InputTuple,
      StoryCapturedEvent.OutputTuple,
      StoryCapturedEvent.OutputObject
    >;
    StoryCaptured: TypedContractEvent<
      StoryCapturedEvent.InputTuple,
      StoryCapturedEvent.OutputTuple,
      StoryCapturedEvent.OutputObject
    >;
  };
}
